#pragma once
#include <Windows.h>
#include <tchar.h>
#include <iostream>
#include <string>
#include <chrono>
#include <gl\GLU.h>
#include "Include\GL\glext.h"
#include "Include\GL\wglext.h"
#include "window.h"
#include "windowclass.h"